//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 gameOfLife.rc 使用
//
#define IDC_MYICON                      2
#define IDOKvsSPEED                     3
#define IDP1OK                          4
#define IDPlayerOK                      4
#define IDP2OK                          5
#define ID_START                        6
#define ID_STOP                         7
#define IDlizi                          8
#define ID_STARTSERVER                  8
#define ID_STARTCLIENT                  11
#define IDD_GAMEOFLIFE_DIALOG           102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDI_LINico                      108
#define IDC_GAMEOFLIFE                  109
#define IDR_MAINFRAME                   128
#define IDB_LINbmp                      131
#define IDI_SMALL                       132
#define IDB_LINbmpPro                   133
#define IDD_VS                          134
#define IDD_SINGLE                      135
#define IDD_VSONLINESET                 136
#define IDD_COLOR                       137
#define IDR_GAME                        138
#define IDD_CREATEROOM                  139
#define IDR_GAMEONLINE                  139
#define IDD_JOINROOM                    140
#define IDD_VSONLINE                    141
#define IDC_EDITvsSIZE                  1000
#define IDC_EDITvsSPEED                 1001
#define IDC_P1ATT                       1002
#define IDC_P1DEF                       1003
#define IDC_CHARA                       1004
#define IDC_P1MUV                       1005
#define IDC_P1SUV                       1006
#define IDOKvsSIZE                      1007
#define IDC_P2ATT                       1008
#define ID_COLOR                        1008
#define IDC_P2DEF                       1009
#define IDC_P2MUV                       1010
#define IDC_P2SUV                       1011
#define IDvsUP                          1012
#define IDvsDOWN                        1013
#define IDvsOnlineCREATE                1013
#define IDvsLEFT                        1014
#define IDvsOnlineJOIN                  1014
#define IDvsRIGHT                       1015
#define ID_SUBATT                       1016
#define ID_ADDATT                       1017
#define ID_SUBDEF                       1018
#define ID_ADDDEF                       1019
#define ID_SUBMUV                       1020
#define IDC_PLAYERNUMBERTEXT            1021
#define ID_ADDMUV                       1021
#define IDC_PLAYERNUMBER                1022
#define ID_SUBSUV                       1022
#define IDC_LOCALIPTEXT                 1023
#define IDvsRIGHT5                      1023
#define ID_ADDSUV                       1023
#define IDC_LOCALIP                     1024
#define IDC_ROOMIPTEXT                  1025
#define IDC_IPADDRESS1                  1026
#define IDC_ROOMIP                      1026
#define ID_CNT                          1028
#define ID_TIMER                        32771
#define ID_TIMER2                       32772
#define ID_SAVE                         32773
#define ID_EDIT1                        32774
#define ID_EDIT1OK                      32776
#define ID_EDIT2                        32778
#define ID_EDIT2OK                      32779
#define ID_TITLE1                       32780
#define ID_TITLE2                       32781
#define ID_OUTPUT1                      32782
#define ID_OUTPUT2                      32783
#define ID_DOING                        32784
#define ID_OUTPUT5                      32784
#define ID_OUTPUT                       32784
#define ID_TITLE3                       32785
#define ID_OUTPUT6                      32785
#define ID_EDIT3X                       32786
#define ID_EDIT3Y                       32787
#define ID_EDIT3OK                      32788
#define ID_OUTPUT3                      32789
#define ID_TITLE4                       32790
#define ID_EDIT4X                       32791
#define ID_EDIT4Y                       32792
#define ID_EDIT4OK                      32793
#define ID_OUTPUT4                      32794
#define ID_VS                           32795
#define ID_TIMER3                       32796
#define ID_SINGLE                       32797
#define ID_SINGLEBUTTON                 32798
#define ID_32798                        32798
#define ID_VSMODE                       32799
#define ID_32799                        32799
#define ID_VSOnline                     32801
#define IDM_SAVE                        32802
#define IDM_LOAD                        32803
#define ID_32806                        32806
#define ID_32807                        32807
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        145
#define _APS_NEXT_COMMAND_VALUE         32808
#define _APS_NEXT_CONTROL_VALUE         1029
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
